Update phpcs.yml
Fixing the composer install process for good.

diff --git a/assets/.github/workflows/phpcs.yml b/assets/.github/workflows/phpcs.yml
--- a/assets/.github/workflows/phpcs.yml
+++ b/assets/.github/workflows/phpcs.yml
@@ -20,9 +20,20 @@ jobs:
       # Need to install Composer to be able to add the coding standards rules.
       - name: Installing Composer
         run: |
+          EXPECTED_CHECKSUM="$(php -r 'copy("https://composer.github.io/installer.sig", "php://stdout");')"
           php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
-          php composer-setup.php
-          php -r "unlink('composer-setup.php');"
+          ACTUAL_CHECKSUM="$(php -r "echo hash_file('sha384', 'composer-setup.php');")"
+
+          if [ "$EXPECTED_CHECKSUM" != "$ACTUAL_CHECKSUM" ]
+          then
+              >&2 echo 'ERROR: Invalid installer checksum'
+              rm composer-setup.php
+              exit 1
+          fi
+          php composer-setup.php --quiet
+          RESULT=$?
+          rm composer-setup.php
+          exit $RESULT
 
       - name: Downloading and installing PHP_CodeSniffer and the Drupal coding standards rules
         run: |
